# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'CachingTestProject' do
    pod 'fk-ios-lib-caching', :path => "../fk-ios-lib-caching.podspec"
end

target 'CachingTestProjectTests' do
    pod 'fk-ios-lib-caching', :path => "../fk-ios-lib-caching.podspec"
end 